status = [
           "BuildAndTest (lxd:ubuntu-20.04:...:gcc)",
           "BuildAndTest (lxd:ubuntu-22.04:...:gcc)",
           "BuildAndTest (lxd:ubuntu-22.10:...:gcc)",
           "BuildAndTest (lxd:ubuntu-22.10:...:clang)",
           "BuildAndTest (lxd:fedora-36:...:gcc)",
           "BuildAndTest (lxd:fedora-37:...:gcc)",
           "BuildAndTest (lxd:alpine-3.15:...:gcc)"
         ]
block-labels = [ "no-merge" ]
timeout-sec = 1800
delete-merged-branches = true
update_base_for_deletes = true
