name: Spread

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number && format('pr{0}', github.event.number) || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
    - main
    - release/[0-9]+.[0-9]+
    tags:
    - v[0-9]+[0-9]+.[0-9]+
  merge_group:
    types: [checks_requested]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions: {}

jobs:
  BuildAndTest:
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        spread-task:
        - lxd:...:debian_sid
        - lxd:...:ubuntu
        - lxd:...:ubuntu_arm64
        - lxd:...:ubuntu_armhf
        - lxd:...:ubuntu_devel
        - lxd:...:ubuntu_proposed
        - lxd:alpine-3.24:...:default
        - lxd:alpine-edge:...:default
        - lxd:archlinux-cloud:...:default
        - lxd:fedora-44:...:default
        - lxd:fedora-rawhide:...:default
        - lxd:ubuntu-26.04:...:clang
        - lxd:ubuntu-devel:...:clang

    runs-on: ubuntu-26.04

    env:
      DEBFULLNAME: "Mir CI Bot"
      DEBEMAIL: "mir-ci-bot@canonical.com"

    steps:
    - name: Set up LXD
      uses: canonical/setup-lxd@8c6a87bfb56aa48f3fb9b830baa18562d8bfd4ee  # v1
      with:
        channel: stable

    - name: Set up Spread
      run: |
        sudo snap install spread-mir-ci
        lxc profile set default \
          security.nesting=true \
          security.privileged=true

    - name: Check out code
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
      with:
        persist-credentials: false

    - name: Run Spread task
      run: snap run spread-mir-ci.spread -reuse -v ${{ matrix.spread-task }}

    - if: ${{ failure() && runner.debug }}
      name: Setup tmate session
      uses: mxschmitt/action-tmate@35b54afac29c97fb54faba5b513f8fbd1882f113  # v3.24
      with:
        limit-access-to-actor: true
