name: Build a tarball

on:
  push:
    tags:
    - v[0-9]+.[0-9]+.[0-9]+
  workflow_dispatch:
    inputs:
      version:
        description: The version to build the tarball for
        required: true

permissions: {}

jobs:
  BuildTarball:
    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
    - name: Determine version to build
      id: get-version
      env:
        INPUTS_VERSION: ${{ inputs.version }}
      run: |
        if ${{ github.event_name == 'push' }}; then
          version="$( echo "${GITHUB_REF}" | sed 's@^refs/tags/v@@' )"
        else
          version="${INPUTS_VERSION}"
        fi

        # assert it's a version number
        set -x
        [[ ${version} =~ ^[0-9]+.[0-9]+.[0-9]+$ ]] && echo "version=${version}" >> $GITHUB_OUTPUT

    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@2dc316deee8e90f13e1a351ab510b4d5bc0c82cd  # v7.0.0
      with:
        gpg_private_key: ${{ secrets.MIR_BOT_GPG_PRIVATE_KEY }}

    - name: Check out code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      with:
        ref: v${{ steps.get-version.outputs.version }}
        persist-credentials: false

    - name: Build the tarball
      env:
        VERSION: ${{ steps.get-version.outputs.version }}
      run: |
        ./tools/make_release_tarball --skip-checks
        gpg --detach-sig --sign --output wlcs-${VERSION}.tar.xz.asc wlcs-${VERSION}.tar.xz

    - name: Store the tarball and signature
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f  # v7.0.0
      with:
        name: wlcs-${{ steps.get-version.outputs.version }}
        path: |
          wlcs-${{ steps.get-version.outputs.version }}.tar.xz
          wlcs-${{ steps.get-version.outputs.version }}.tar.xz.asc
